[project]
name = "pathql"
version = "0.1.0"
description = "A Python project for pathql."
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
requires-python = ">=3.14"

[tool.setuptools.packages.find]
where = ["src"]
